/**
 * Mapeamento de nomes de exercícios para seus tipos (compound/isolation)
 * Gerado automaticamente baseado no seed.ts
 */

export const EXERCISE_TYPES_MAP: { [exerciseName: string]: string } = {
  'Ab wheel': 'isolation',
  'Abdominal infra': 'isolation',
  'Abdominal supra': 'isolation',
  'Abdução de perna': 'isolation',
  'Adutor máquina': 'isolation',
  'Afundo': 'compound',
  'Agachamento búlgaro': 'compound',
  'Agachamento frontal': 'compound',
  'Agachamento livre': 'compound',
  'Agachamento sumô': 'compound',
  'Barra fixa': 'compound',
  'Cadeira extensora': 'isolation',
  'Cadeira flexora': 'isolation',
  'Crucifixo halteres': 'isolation',
  'Crunch na máquina': 'isolation',
  'Crunch polia joelhado': 'isolation',
  'Desenvolvimento Arnold': 'compound',
  'Desenvolvimento com barra': 'compound',
  'Desenvolvimento halteres sentado': 'compound',
  'Desenvolvimento máquina': 'compound',
  'Elevação frontal halteres': 'isolation',
  'Elevação lateral com cabo': 'isolation',
  'Elevação lateral halteres': 'isolation',
  'Elevação lateral máquina': 'isolation',
  'Elevação lateral polia': 'isolation',
  'Elevação pélvica': 'compound',
  'Encolhimento de ombros': 'isolation',
  'Extensão de perna unilateral': 'isolation',
  'Extensão lombar banco romano': 'isolation',
  'Face pull': 'isolation',
  'Flexão de braço': 'compound',
  'Flexão de perna deitado': 'isolation',
  'Hack squat': 'compound',
  'Hip thrust barra': 'compound',
  'Leg press': 'compound',
  'Leg press 45°': 'compound',
  'Leg raise': 'isolation',
  'Levantamento terra romeno': 'compound',
  'Mesa flexora': 'isolation',
  'Mountain climber': 'isolation',
  'Panturrilha em pé': 'isolation',
  'Panturrilha leg press': 'isolation',
  'Panturrilha no leg press': 'isolation',
  'Panturrilha sentado': 'isolation',
  'Panturrilha unilateral': 'isolation',
  'Paralelas': 'compound',
  'Peck deck': 'isolation',
  'Prancha': 'isolation',
  'Pulldown pull-over': 'compound',
  'Puxada frontal pegada aberta': 'compound',
  'Puxada frontal pegada fechada': 'compound',
  'Puxada no pulley': 'compound',
  'Remada alta': 'compound',
  'Remada baixa máquina': 'compound',
  'Remada cavalinho T-bar': 'compound',
  'Remada com cabo': 'compound',
  'Remada curvada barra': 'compound',
  'Remada unilateral halter': 'compound',
  'Reverse pec deck': 'isolation',
  'Rosca alternada halteres': 'isolation',
  'Rosca com cabo': 'isolation',
  'Rosca concentrada': 'isolation',
  'Rosca direta barra': 'isolation',
  'Rosca martelo': 'isolation',
  'Rosca no banco Scott': 'isolation',
  'Russian twist': 'isolation',
  'Stiff': 'compound',
  'Supino com pegada fechada': 'compound',
  'Supino declinado barra': 'compound',
  'Supino declinado halteres': 'compound',
  'Supino inclinado halteres': 'compound',
  'Supino inclinado máquina': 'compound',
  'Supino reto barra': 'compound',
  'Supino reto halteres': 'compound',
  'Terra tradicional': 'compound',
  'Tríceps coice': 'isolation',
  'Tríceps francês': 'isolation',
  'Tríceps mergulho máquina': 'isolation',
  'Tríceps pulley': 'isolation',
  'Tríceps testa barra EZ': 'isolation',
};

/**
 * Retorna o tipo do exercício baseado no nome
 * @param exerciseName Nome do exercício
 * @returns 'compound' ou 'isolation' (default: 'isolation')
 */
export function getExerciseType(exerciseName: string): string {
  return EXERCISE_TYPES_MAP[exerciseName] || 'isolation';
}
